### ISSUE TITLE
unknown to the library visdom_logger

### ISSUE THREAD

**Issue by OverVan** [mboudiaf/TIM#10]
Hello, I have a trivial problem about library `visdom_logger`.
I have never seen this library, and also I did not find it in the PYPI.
Could you please tell what it is and where I can download it? 
Thank you!

**Comment by mboudiaf** [comment]
Hi,

Sorry for the confusion, it's true it's not widely used. Please use the following command to install it:
```
pip install git+https://github.com/luizgh/visdom_logger

```
I will update the README.md.
Best !
