### ISSUE TITLE
ModuleNotFoundError: No module named 'visdom_logger'

### ISSUE THREAD

**Issue by Yanfei-Qin** [mboudiaf/TIM#2]
Traceback (most recent call last):
  File "/home/dell/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dell/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/data/qinyanfei/code/TIM-master/src/main.py", line 8, in <module>
    from visdom_logger import VisdomLogger
ModuleNotFoundError: No module named 'visdom_logger'

Is the module missing？

**Comment by mboudiaf** [comment]
1) If you activate the environment provided as described in the README.md, visdom_logger will already be installed.

2) Alternatively, if you haven't downloaded the environment, you can install visdom_logger using this command:
 ```
pip install git+https://github.com/luizgh/visdom_logger.git
 ```

**Comment by Yanfei-Qin** [comment]
Thank you. Your reply helped me a lot

**Comment by Yanfei-Qin** [comment]
thank you，best wishes for you


| |
秦雁飞
|
|
qyf532356675@163.com
|
签名由网易邮箱大师定制
On 12/21/2020 22:06，Malik Boudiaf<notifications@github.com> wrote：

If you activate the environment provided as described in the README.md, visdom_logger will already be installed.

Alternatively, if you haven't downloaded the environment, you can install visdom_logger using this command:

pip install git+https://github.com/luizgh/visdom_logger.git
