### ISSUE TITLE
AttributeError: 'Trainer' object has no attribute 'meta_val_interval'

### ISSUE THREAD

**Issue by Yanfei-Qin** [mboudiaf/TIM#4]
when i run training code：bash scripts/train/resnet18.sh，
have a problem;

ERROR - FSL training - Failed after 0:04:19!
Traceback (most recent calls WITHOUT Sacred internals):
File "/home/data/qinyanfei/code/TIM-master/src/main.py", line 118, in main
if (epoch) % trainer.meta_val_interval == 0:
AttributeError: 'Trainer' object has no attribute 'meta_val_interval'

can you answer me？

**Comment by mboudiaf** [comment]
This should be fixed. Please pull again and let me know if you still face problems.

Malik
