### ISSUE TITLE
How can I adapt this method to another dataset?

### ISSUE THREAD

**Issue by Phoveran** [mboudiaf/TIM#7]
I want to adapt this dataset to  [Ali Aluminum Dataset](https://tianchi.aliyun.com/competition/entrance/231682/information).
Now I've made my own split file, written my own al_tianchi.sh like:
```bash
python3 -m src.main \
		with dataset.path="/path/to/al_tianchi" \
		visdom_port=8097 \
		dataset.split_dir="split/al_tianchi" \
		ckpt_path="checkpoints/al_tianchi/softmax/resnet18" \
		dataset.batch_size=128 \
		dataset.jitter=True \
		model.arch='resnet18' \
		model.num_classes=10 \
		optim.scheduler="multi_step" \
		epochs=90 \
		trainer.label_smoothing=0.1
```
and trained my own resnet18 model(as I understand, the backbone).
What should I do next to test TIM on this dataset?
Sorry for my bad English, and sorry for my disturbing.
Best Wishes for You :)

**Comment by mboudiaf** [comment]
Hi,

I guess you could try to modify the evaluation script, for instance this one : https://github.com/mboudiaf/TIM/blob/7809262292726ba08764c55751a538e74a54c111/scripts/evaluate/tim_gd/mini.sh#L4
and run this. If your splits have been properly made, and the dataset is not too huge, this should be fine. Let me know if that works for you :)
Best

**Comment by Phoveran** [comment]
Hi,
I've made my script as you depicted, getting this error:
```
ERROR - FSL training - Failed after 0:00:17!
Traceback (most recent calls WITHOUT Sacred internals):
  File "/home/stan/work/TIM/src/main.py", line 98, in main
    results = evaluator.run_full_evaluation(model=model,
  File "/home/stan/work/TIM/src/eval.py", line 63, in run_full_evaluation
    tasks = self.generate_tasks(extracted_features_dic=extracted_features_dic,
  File "/home/stan/work/TIM/src/eval.py", line 237, in generate_tasks
    task_dic = self.get_task(shot=shot, extracted_features_dic=extracted_features_dic)
  File "/home/stan/work/TIM/src/eval.py", line 206, in get_task
    indexes = np.random.choice(a=class_indexes, size=shot + query_shots, replace=False)
  File "mtrand.pyx", line 954, in numpy.random.mtrand.RandomState.choice
ValueError: Cannot take a larger sample than population when 'replace=False'
```
I think that's somehow connected with my dataset size.
I have:
1. 10 types of base class, each containing 50~500 images
2. 3 types of validation class, each containing 50~500 images
3. 17 novel classes, each containing less than 50 images

And I've trained my resnet18 with `num_classes=10`.
Could you please let me know if you get any idea?

**Comment by mboudiaf** [comment]
No your dataset is actually pretty small. The problem here is that certain of your test classes don't even have enough samples to form a task. For instance if you're making 5-way 1-shot tasks with 15 query samples (default setting) you should make sure each class has a least 1 + 15 = 16 samples per class. If that is not the case, I would advise using less query shots, by setting the option eval.query_shots to a lower number. Let me know :)

**Comment by Phoveran** [comment]
Finally Got it Running! Really Appreciate for Your Help!
