### ISSUE TITLE
About Adapting This Method to Other Datasets

### ISSUE THREAD

**Issue by Phoveran** [mboudiaf/TIM#8]
Hi,
In #7 I've said I plan to adapt this method to another aluminum dataset.
I've already done that, yielding a rather great result(5 way 1 shot with accuracy **0.5171**, 5 way 5 shot with accuracy **0.6927**).
There is a question: in the backbone training stage, the highest accuracy it achieved is about **0.64**(below 0.6927), is this abnormal?
And another interesting thing is, when I use backbone trained with the aluminum dataset to evaluate on [NEU-CLS](http://faculty.neu.edu.cn/yunhyan/NEU_surface_defect_database.html) dataset, it achieved an incredible accuracy of [**0.7010**, **0.8141**]!!!
Best

**Comment by mboudiaf** [comment]
Hey,

Thanks for your follow-up ! 

> I've already done that, yielding a rather great result(5 way 1 shot with accuracy 0.5171, 5 way 5 shot with accuracy 0.6927).
> There is a question: in the backbone training stage, the highest accuracy it achieved is about 0.64(below 0.6927), is this abnormal?

This looks very normal to me, as the accuracy during the training stage is computed on the validation split, which is supposedly different from the testing one. Therefore, observing a difference is fine ;) 


> And another interesting thing is, when I use backbone trained with the aluminum dataset to evaluate on NEU-CLS dataset, it achieved an incredible accuracy of [0.7010, 0.8141]!!!

That is great. Have you had the opportunity to produce other methods in this scenario for comparison ?

Best
